namespace DOMSLibrary
{
    internal enum TgDeliveryDataItemIds
    {
        TGDDI_PRODUCT_CODE = 1,
        TGDDI_DELIVERY_SEQ_NO = 2,
        TGDDI_START_DATE_AND_TIME = 3,
        TGDDI_START_PROD_VOL = 4,
        TGDDI_START_WATER_VOL = 5,
        TGDDI_START_TEMP = 6,
        TGDDI_STOP_DATE_AND_TIME = 7,
        TGDDI_STOP_PROD_VOL = 8,
        TGDDI_STOP_WATER_VOL = 9,
        TGDDI_STOP_TEMP = 16,
        TGDDI_DELIVERED_VOL = 17,
        TGDDI_DELIVERY_REPORT_SEQ_NO = 18,
        TGDDI_RETURN_DATA = 19,
        TGDDI_START_PROD_DENSITY = 20,
        TGDDI_STOP_PROD_DENSITY = 21,
        TGDDI_START_PROD_MASS = 22,
        TGDDI_STOP_PROD_MASS = 23,
        TGDDI_START_PROD_TC_VOL = 24,
        TGDDI_STOP_PROD_TC_VOL = 25,
        TGDDI_DELIVERED_TC_VOL = 32,
        TGDDI_ADJUSTED_VOL = 33,
        TGDDI_ADJUSTED_TC_VOL = 34,
        TGDDI_SALE_VOL_DURING_DELIVERY = 35,
        TGDDI_START_PROD_TC_DENSITY = 36,
        TGDDI_STOP_PROD_TC_DENSITY = 37
    }
}
